### ISSUE TITLE
Enabling 'MS'

### ISSUE THREAD

**Issue by simoneliasen** [moraieu/query-selector#7]
Hi i'm trying to implement the code, but with 'MS' feature, which i can see traces of in your code, inspired from the Informer.

I tried adding a 'multiuni' prediction type, alongside the 'multi' and 'uni' one and have changed my setting accordingly to use 'multiuni':

```
elif self.prediction_type == 'multiuni':
            sys.argv.extend(["--features", 'MS'])
            sys.argv.extend(["--input_len", '7', "--output_len", "1"])
```

I am however, consistently getting issues, most recently, triggering an assertion in the code:

```
File "train.py", line 178, in preform_experiment
    len(train_data.data_y[0]), args.output_len)
AssertionError: Dataset contains output vectors of length 7 while output_len is set to 1
```

Is there anyway that you could guide me to the implementation of MS?

Best regards

**Comment by j-klm** [comment]
Check the latest version. Multiuni should work.
